name: tekartik_pub
version: 1.0.0
description: Pub and package helpers
homepage: https://github.com/tekartik/pub.dart
publish_to: none

environment:
  sdk: ^3.9.0
dependencies:
  dev_build: ">=1.1.2"
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  yaml: ">=3.1.2"
  fs_shim: '>=2.4.0-1'
  pub_semver: ">=2.1.4"
  args: ">=2.6.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.9.8'

dev_dependencies:
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
    version: '>=0.4.3'
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: '>=0.10.2'
  async: '>=2.0.7'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
test_dependencies:
- process_run

# dependency_overrides:
#  process_run:
#    path: ../../../github.com/tekartik/process_run.dart
#  dev_test:
#    path: ../dev_test.dart/dev_test
#  process_run:
#    git: https://github.com/tekartik/process_run.dart
#  fs_shim:
#    git: https://github.com/tekartik/fs_shim.dart
#  fs_shim:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim.dart
